更改安卓端的文件访问方式，优化导入逻辑
venera-app/venera pull request #64
Opened 2024-11-21 10:08 UTC by pkuislm

使用saf授权目录访问，可以做到精确的权限控制，用户还可从设置中撤销已授权的目录：
![image](https://github.com/user-attachments/assets/923fc4da-0da0-416a-af98-35619bc3c891)
此外，优化漫画导入逻辑以及漫画封面选择逻辑

2024-11-22 13:50 UTC, wgh136 commented on lib/foundation/local.dart
> +    var directory = openDirectoryPlatform(FilePath.join(path, comic.directory));
没有处理comic.directory是绝对路径的情况, 这里似乎`package:path`帮助处理了错误, 在windows上工作正常, 但不能信任它, 需要修改

2024-11-22 14:00 UTC, wgh136 commented on lib/utils/import_comic.dart
>      if (!(await directory.exists())) return null;
在我的手机(Android 14)上试了一下, 导入漫画选择不复制时这里判断目录不存在

2024-11-22 14:15 UTC, wgh136 commented on lib/utils/io.dart
> +        directory = (await AndroidDirectory.pickDirectory())?.path;
能否让返回的路径加上一个scheme, 例如`android://primary/...`, 从而能够将其与普通的路径区分, 避免混乱
下面的`openDirectoryPlatform`, `openFilePlatform` 也就可以直接根据前缀判断

2024-11-22 14:18 UTC, wgh136 requested changes
目前此功能在我的Android手机上完全不可用
需要修改

2024-11-22 15:46 UTC, pkuislm commented on lib/utils/io.dart
> +        directory = (await AndroidDirectory.pickDirectory())?.path;
已在库flutter_saf中修改

2024-11-22 16:24 UTC, pkuislm commented on lib/utils/import_comic.dart
>      if (!(await directory.exists())) return null;
使用Android14模拟器未能复现（descriptor存在且能正常导入），需要提供详细信息。
![image](https://github.com/user-attachments/assets/a378ded8-4870-4470-81ab-1de19781492a)

2024-11-23 02:51 UTC, wgh136 commented on lib/utils/import_comic.dart
> +    coverPath = fileList.firstWhereOrNull((l) => l.startsWith('cover')) ?? fileList.first;
选择空目录时这里会出错

2024-11-23 02:52 UTC, pkuislm commented on lib/utils/import_comic.dart
> +    coverPath = fileList.firstWhereOrNull((l) => l.startsWith('cover')) ?? fileList.first;
应为该函数逻辑问题，当目录为空时不应走到此处

2024-11-23 02:54 UTC, wgh136 commented on lib/utils/io.dart
> +      return Directory(path);
建议直接根据前缀判断是不是SAF的路径, 避免多调一次原生代码

2024-11-23 03:05 UTC, merged